[config]
schemaVersion = "0.0.1"

[package]
namespace = "deca"
name = "VampireCommandFramework"
versionNumber = "0.8.0"
description = "Command framework for developers to easily create universal commands for their plugins."
websiteUrl = "https://github.com/decaprime/VampireCommandFramework"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack_V_Rising = "1.668.5"

[build]
icon = "./images/logo_256.png"
readme = "./README.md"
outdir = "./build"

[[build.copy]]
source = "./dist"
target = ""

[publish]
repository = "https://v-rising.thunderstore.io"
communities = ["v-rising"]
categories = ["gloomrot-update", "mods", "server"]
